### ISSUE TITLE
Autolint seems to ignore .eslintrc

### ISSUE THREAD

**Issue by arielserafini** [dojoteef/neomake-autolint#10] opened 2017-01-17 11:18 UTC
With neomake-autolint enabled, I get plenty of errors such as
`javascript_eslint_autolint: Expected indentation of 4 spaces but found 2. (indent)`, but the Neomake command gives me a very different output, with no indentation errors (as I would expect).

**Comment by dojoteef** [comment] 2017-01-17 15:16
This is a duplicate of #6. My (suggestion)[https://github.com/dojoteef/neomake-autolint/issues/6#issuecomment-268365813] could be of help for now. I am trying to figure out an extensible solution for this issue which is why this isn't fixed yet. Please direct any further comments or suggestions for this in #6.

**Closed as completed by dojoteef** 2017-01-17 15:16 UTC
Labels: duplicate
